repos:
  - repo: local
    hooks:
      - id: cargo-fix
        name: cargo fix
        entry: cargo fix --allow-dirty --allow-staged
        language: system
        types: [ rust ]
        pass_filenames: false

      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all
        language: system
        types: [ rust ]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy -- -D warnings -A clippy::upper_case_acronyms
        language: system
        types: [ rust ]
        pass_filenames: false